app/views/product/_product_index_topbar.html.erb
Remove restrictions allowing a PM to be able to create a project
=> Remove restrictions allowing a PM to be able to create a project

config/deploy.rb, config/deploy/staging.rb, config/environments/staging.rb
This pull request introduces configuration changes to support a dedicated staging environment for the application. It adds new environment and deployment files, updates deployment settings, and configures Rails to behave in a production-like manner for staging. The most important changes are grouped below:
**Staging Environment Setup:**
* Added `config/environments/staging.rb` to define staging-specific Rails settings, including caching, asset compilation, logging, mailer configuration, and storage service. This ensures the staging environment closely mimics production behavior while remaining isolated.
**Deployment Configuration:**
* Added `config/deploy/staging.rb` to specify the staging server, deployment branch, linked files and directories, and environment variables for Capistrano …
=> Staging enhancement

app/controllers/test_controller.rb, app/helpers/test_helper.rb, app/mailers/error_notifier_mailer.rb, app/services/error_logger.rb, config/initializers/error_tracking.rb, config/routes.rb, db/schema.rb, spec/helpers/test_helper_spec.rb, spec/requests/test_spec.rb
This pull request introduces a new error tracking and notification system for both web requests and background jobs. It adds centralized error logging, automated email notifications for exceptions, and includes a test controller for simulating errors. The changes are grouped into error handling infrastructure, notification, and testing.
**Error handling infrastructure:**
* Added `ErrorLogger` service in `app/services/error_logger.rb` to log exceptions and their context to a dedicated log file (`production_errors.log`).
* Created an initializer in `config/initializers/error_tracking.rb` to subscribe to web request and Sidekiq job errors, logging them and triggering notifications.
**Error notification:**
* Added `ErrorNotifierMailer` in `app/mailers/error_notifier_mailer.rb` to send emails …
=> First part of error logging

app/controllers/health_controller.rb, app/helpers/health_helper.rb, app/jobs/application_job.rb, app/mailers/error_notifier_mailer.rb, app/middleware/error_notifier_middleware.rb, app/services/error_logger.rb, app/services/error_payload.rb, app/services/safe_notifier.rb, config/application.rb, config/initializers/error_notifier_middleware.rb, config/initializers/error_tracking.rb, config/initializers/sentry.rb, config/routes.rb, spec/helpers/health_helper_spec.rb, spec/requests/health_spec.rb
This pull request introduces a robust error notification and logging system across web requests and background jobs, adds a new health check endpoint, and updates supporting infrastructure and tests. The main themes are error handling improvements, health check functionality, and related configuration updates.
**Error Handling & Notification Improvements:**
* Introduced `ErrorNotifierMiddleware` to log errors and send email notifications for unhandled exceptions in web requests, with detailed request context. Inserted this middleware at the start of the middleware stack. [[1]](diffhunk://#diff-eafa4af870ec1397aadbcb450ceb569927b7cb4c970b91d030507e814603a9f5R1-R19) [[2]](diffhunk://#diff-c1fd91cb1911a0512578b99f657554526f3e1421decdb9e908712beab57e10f9R22-R24) …
=> Add the controls for the error reporting

app/controllers/product_controller.rb, app/jobs/daily_report_job.rb, app/mailers/user_mailer.rb, app/views/user_mailer/assign_product_email.html.erb, app/views/user_mailer/assignment_email.html.erb, app/views/user_mailer/create_ticket_email.html.erb, app/views/user_mailer/daily_ticket_email.html.erb, app/views/user_mailer/edit_ticket_email.html.erb, app/views/user_mailer/finance_sales_email.html.erb, app/views/user_mailer/mention_user_in_issue.html.erb, app/views/user_mailer/morning_ticket_email.html.erb, app/views/user_mailer/new_comment_email.html.erb, app/views/user_mailer/status_update_email.html.erb, app/views/user_mailer/ticket_assignment_email.html.erb, config/initializers/globalid_rescue.rb
This pull request focuses on improving the robustness and clarity of email notifications and job executions throughout the application. The main changes ensure that emails gracefully handle missing or incomplete user and product data, and that background jobs using GlobalID do not fail noisily when records are missing. These updates enhance user experience and system reliability.
**Email robustness and user/product data handling:**
* Updated all mailer views (e.g., `assignment_email.html.erb`, `create_ticket_email.html.erb`, `finance_sales_email.html.erb`, etc.) to use safe navigation and fallback values for user and product names, ensuring emails display sensible defaults when data is missing or incomplete. [[1]](diffhunk://#diff-988ff2bf14e2e7201dcc5f1bd7bcf93b039d8c79821481197e22378bcd3 …
=> Fix the emails spamming error

app/models/defect.rb, app/views/defect/_form.html.erb, app/views/defect/new.html.erb
Make sure that the defect creation form matches the given UI provided.
Matches from the issue #37
=> Defects create newui popup

app/controllers/defect_controller.rb, app/models/defect.rb, app/models/status.rb, app/views/defect/_form.html.erb, db/migrate/20250821120959_create_defects_statuses_join_table.rb, db/schema.rb
Add the status removing it from the defects and created a join table
=> Add defect jointable tostatuses

app/controllers/data_center_controller.rb, app/controllers/defect_controller.rb, app/views/data_center/user_report.html.erb, app/views/defect/_assign_defect_status.html.erb, app/views/defect/_defect.html.erb, app/views/defect/_form.html.erb, app/views/defect/_user_initials.html.erb, app/views/defect/show.html.erb, config/routes.rb
This pull request introduces several enhancements and fixes to the user and defect reporting features, focusing on improved data aggregation, more flexible status assignment for defects, and better presentation of associated users and activities. The changes include backend logic updates, new routes and controller actions, and UI improvements for displaying events, issues, and user information.
* Refactored the `user_report` action in `data_center_controller.rb` to aggregate tickets where the user is the owner, appears on related events, or issues. This provides a more comprehensive view of user activity and ensures correct filtering and grouping by status and client. Events and issues are now also collected for display.
* Updated the user report view (`user_report.html.erb`) to include …
=> Defect user status

app/controllers/defect_controller.rb, app/views/defect/_add_defect.html.erb, app/views/defect/_defect_details.html.erb, app/views/defect/_defect_metadata.html.erb, app/views/defect/_defect_show_top_bar.html.erb, app/views/defect/_defect_sidebar.html.erb, app/views/defect/_defect_statuses.html.erb, app/views/defect/_defect_timeline.html.erb, app/views/defect/_show_assigned_user.html.erb, app/views/defect/show.html.erb
This pull request introduces a significant redesign and refactor of the defect show page, focusing on improved layout, clearer metadata presentation, and enhanced user assignment and status management. The changes streamline the UI, consolidate related information into themed sidebar components, and refine the user assignment logic to ensure only one user is assigned at a time.
**Defect show page redesign and componentization:**
* The main `show.html.erb` layout is restructured to use a sidebar and top bar, separating key sections like summary, content, metadata, assigned users, and status into their own partials for clarity and maintainability. (`app/views/defect/show.html.erb`, `app/views/defect/_defect_sidebar.html.erb`, `app/views/defect/_defect_show_top_bar.html.erb`, …
=> Brighton fix

app/controllers/defect_messages_controller.rb, app/models/defect.rb, app/models/defect_message.rb, app/models/user.rb, app/views/defect/_defect_details.html.erb, app/views/defect/show.html.erb, app/views/defect_messages/_defect_message.html.erb, app/views/defect_messages/_message.html.erb, app/views/defect_messages/_messages.html.erb, app/views/defect_messages/_new_button.html.erb, app/views/defect_messages/create.turbo_stream.erb, app/views/defect_messages/edit.html.erb, app/views/defect_messages/new.html.erb, config/routes.rb, db/migrate/20250822132255_create_defect_messages.rb, db/migrate/20250822133237_add_audit_fields_to_defect_messages.rb, db/schema.rb, spec/models/defect_message_spec.rb
=> Defect communication center

app/controllers/defect_messages_controller.rb, app/views/defect_messages/_message.html.erb, app/views/defect_messages/edit.html.erb, app/views/defect_messages/new.html.erb
Ensure that when a user creates a defect message, it shows them. When you also delete a defect message, it also removes the deleted one from the view.
=> Show defect message on create and on delete

app/controllers/defect_controller.rb, db/seeds.rb
Add QA role and grant it abilities in the controller level
Also, add the role in the seeds file. KIndly run seeds as well in deployment.
=> Add the QA role

app/views/banking_types/_bankingtype_index_topbar.html.erb, app/views/defect/_top_bar.html.erb, app/views/qa_modules/_qamodule_index_topbar.html.erb, app/views/qa_modules/index.html.erb, app/views/qa_modules/show.html.erb
This pull request updates the UI for banking types and QA modules to improve navigation and simplify module listings. The main changes add "Back" buttons for easier navigation, adjust button routes for consistency, and remove the "Parent Module" column from the QA modules index page.
**Navigation improvements:**
* Added a "Back" button linking to the defects index in both `banking_types/_bankingtype_index_topbar.html.erb` and `qa_modules/_qamodule_index_topbar.html.erb` for easier navigation from banking types and QA modules pages. [[1]](diffhunk://#diff-3ddfff4f98460f04edf3e3d64d5aafaa99de126c2756ca2ffb94cfd375b4306cL1-R8) [[2]](diffhunk://#diff-d393734f70c51411a9979f21315df96da274b32730b2b0507b95e62b2f37c0c6L1-R9)
* Added a "Back" button on the QA module show page …
=> Module and banking types Views fixes

app/controllers/defect_controller.rb, app/models/defect.rb, app/views/defect/_defect_show_update_label.html.erb, app/views/defect/_defect_sidebar.html.erb, app/views/defect/_form.html.erb, app/views/defect/edit.html.erb, config/routes.rb, db/migrate/20250829085429_add_labels_to_defects.rb, db/schema.rb
1. Add the labels in the defects resource
2. Add this label to the create and edit form
3. Add a custom method in the defect controller to allow manually editing a label in the defect show
4. Add the ability to add attachments in the defect create form
This references the issue #89
=> Add the Labels and the attachments in the defects resource

app/controllers/defect_controller.rb, app/models/ability.rb, app/views/defect/_defect_show_attachments.html.erb, app/views/defect/_form.html.erb
Add page numbers for the defects show adding next and previous pages
add the validations for the create defects form
=> Defect form validations attachment pagination

app/controllers/application_controller.rb, app/controllers/assurance_controller.rb, app/controllers/defect_controller.rb, app/controllers/test_controller.rb, app/helpers/assurance_helper.rb, app/views/defect/_defect.html.erb, app/views/defect/_defect_index_product.html.erb, app/views/defect/_defect_order_status.html.erb, app/views/defect/_top_bar_show.html.erb, app/views/defect/index_show.html.erb, app/views/tickets/all_tickets_and_no_team_member.html.erb, config/routes.rb, db/schema.rb, spec/helpers/assurance_helper_spec.rb, spec/requests/assurance_spec.rb
This pull request introduces significant enhancements to the defect management features, including improved filtering, grouping, and pagination for defects, as well as related UI updates. It also includes some codebase cleanup and minor consistency improvements.
**Defect Management Features**
* Added a new `index_show` action to `DefectController` that supports advanced filtering (by client, status, search query), user-specific restrictions, grouping, and pagination for defects. This action also prepares distinct statuses for dropdowns and renders the new `index_show` view. [[1]](diffhunk://#diff-dc7c49831e0ad3c9799f5217bbb1c0a4a030855fdaf4eaad445020b5d6b37d17R49-R95) [[2]](diffhunk://#diff-58e8c6fbe175f0c677d82c802110d14dc63c714d3b08a198ade2a249361db6c5R1-R17) …
=> The changes for defects

app/controllers/defect_controller.rb, app/controllers/labels_controller.rb, app/javascript/application.js, app/javascript/controllers/ckeditor_init.js, app/javascript/controllers/label_tomselect_init.js, app/javascript/controllers/modal_controller.js, app/javascript/controllers/trix_custom_formatting_controller.js, app/jobs/merge_duplicate_labels_job.rb, app/models/defect.rb, app/models/defect_label.rb, app/models/label.rb, app/views/defect/_defect_show_update_label.html.erb, app/views/defect/_form.html.erb, app/views/defect/_labels.html.erb, app/views/defect/add_label.turbo_stream.erb, app/views/defect/new.html.erb, app/views/defect/remove_label.turbo_stream.erb, app/views/layouts/application.html.erb, config/routes.rb, db/migrate/20250902074413_create_labels.rb, db/migrate/20250902074635_create_defect_labels.rb, db/migrate/20250902074743_remove_labels_from_defects.rb, db/schema.rb
Includes the Rich text and the labels functionality
Handled in this issue and this #107  one #108 
When you paste, it maintains the structure as shown:
When you create the pasted, it still maintains the structure to some extent
[Screencast from 02-09-2025 03:53:50 ALASIRI.webm](https://github.com/user-attachments/assets/bdd48095-ffd1-429d-8650-0b72bb0e72df)
=> Improveon defect labels

app/views/defect/_defect_show_attachments.html.erb, app/views/defect/_defect_show_update_label.html.erb
This PR handles the first section of this issue #110
=> Defect UI Enhancements: Attachments and preview

app/views/defect/_add_defect.html.erb, app/views/defect/_assign_defect_status.html.erb, app/views/defect/_defect_show_severity.html.erb, app/views/defect/_defect_show_update_label.html.erb, app/views/defect/_defect_sidebar.html.erb, app/views/defect/_show_assigned_user.html.erb
This PR was implemented as per this issue as well #110
=> Defect UI Enhancements: Sidebar Dropdowns

app/controllers/default_defect_assignees_controller.rb, app/controllers/defect_controller.rb, app/javascript/application.js, app/models/default_defect_assignee.rb, app/views/default_defect_assignees/_button.html.erb, app/views/default_defect_assignees/new.html.erb, app/views/defect/_top_bar.html.erb, app/views/defect/new.html.erb, config/routes.rb, db/migrate/20250906063220_create_default_defect_assignees.rb, db/migrate/20250906063803_add_auditability_fields_to_default_defect_assignee.rb, db/schema.rb
Add Defect Default Assignee
Fix the search in the create defect form
Add visual notes to let a user know when they can leave the assignee field blank or not
Run migrations to add a default Defect assignee table
THis handles the issue #176
=> Defect default assignee

app/javascript/application.js, app/views/layouts/application.html.erb
See if this fixes failing JS issues in UAT
=> CKEditor JS fix test

app/views/defect/_defect_metadata.html.erb, app/views/defect/_defect_order_status.html.erb, app/views/defect/_defect_show_top_bar.html.erb, app/views/defect/_top_bar.html.erb
Improvements to the defects show and some areas of the defects as per the breakdown in this issue #214
=> Defectshow pageenhancements

app/controllers/defect_controller.rb, app/controllers/defect_failure_reports_controller.rb, app/controllers/tickets_controller.rb, app/controllers/users_controller.rb, app/models/defect.rb, app/models/defect_failure_report.rb, app/models/defect_message.rb, app/services/defect_record_failure_service.rb, app/views/home/index.html.erb, app/views/product/_add_users.html.erb, app/views/product/_remove_user.html.erb, app/views/tasks/_assign_user.html.erb, app/views/tickets/_assign_people_tickets.html.erb, app/views/users/_user_list.html.erb, config/routes.rb
This pull request introduces several improvements and minor fixes across controllers, services, models, and views. The main changes focus on standardizing string quotes to single quotes, improving authorization logic, adding a user password reset feature, and making minor UI and copy updates.
**User Management Improvements:**
* Added a new `reset_user_password` action to the `UsersController`, allowing admins to reset a user's password. Corresponding UI elements and routes have been added to support this feature. [[1]](diffhunk://#diff-cfdccd0a9d5df5a43aaad2a35d36ebbe187c52ad5fdc9846fa189d04537adb6eR133-R139) [[2]](diffhunk://#diff-c5b702fd120f5b83cd4b4938e7df81bd1b6482766bb0aae654411618023fd54aR27-R29) [[3]](diffhunk://#diff-c5b702fd120f5b83cd4b4938e7df81bd1b6482766bb0aae654411618023fd54a …
=> Reset user all

app/controllers/ticket_feedbacks_controller.rb, app/controllers/tickets_controller.rb, app/javascript/controllers/star_rating_controller.js, app/models/ticket.rb, app/models/ticket_feedback.rb, app/services/ticket_record_feedback_service.rb, app/views/ticket_feedbacks/_list.html.erb, app/views/tickets/_feedback_count.html.erb, app/views/tickets/_feedback_modal.html.erb, app/views/tickets/_feedback_row.html.erb, app/views/tickets/_modal_empty.html.erb, app/views/tickets/show.html.erb, config/routes.rb, db/migrate/20250911134356_create_ticket_feedbacks.rb, db/schema.rb
- Added client feedback section with consistent Tailwind styling  
- Displayed rating as SVG stars instead of plain numbers  
- Applied max height with vertical scroll for feedback list  
- Ensured spacing and typography matches other sections  
References issue #206
=> Ticket Feedback on Status close

app/controllers/qa_modules_controller.rb, app/views/qa_modules/index.html.erb
Add a way to preview the submodules of a module while you are in the qa modules index view. THis references the issue #216
=> Qamodule and submodules preview

app/controllers/ticket_feedbacks_controller.rb, app/controllers/tickets_controller.rb, app/models/ticket.rb, app/models/ticket_feedback.rb, app/services/ticket_record_feedback_service.rb
=> Fix found Rubocop offences

app/views/defect/_form_labels.html.erb, app/views/defect/edit.html.erb, app/views/defect/new.html.erb
=> Defect form improvements

app/controllers/reports_controller.rb
This pull request updates the logic in the `ReportsController#index` action to improve how products are filtered and how defect data is grouped. The most significant change is the addition of a requirement that products must have published defects to be included in the report, alongside their status checks.
**Product filtering improvements:**
* Updated the product selection logic in `reports_controller.rb` to require that products not only have relevant statuses (`Pre Quality Assurance` or `End Of Quality Assurance`) but also have at least one published defect associated with them. This ensures that only products with actionable defect data are shown in reports.
**Defect grouping logic:**
* Cleaned up the code for grouping defects by status in the `index` action, removing unnecessary …
=> Implement searchable dropdowns for adding and removing users

app/javascript/controllers/assignee_editor_controller.js, app/javascript/controllers/label_editor_controller.js, app/views/defect/_defect_show_update_label.html.erb, app/views/defect/_defect_sidebar.html.erb, app/views/defect/_labels.html.erb, app/views/defect/_show_assigned_user.html.erb
=> Searchable Dropdowns in Defects for assignee and labels

app/controllers/defect_controller.rb, app/controllers/reports_controller.rb, app/views/reports/_defect_per_user.html.erb
This pull request introduces improvements to defect filtering and reporting in the application, focusing on correcting query logic and enhancing the reporting interface. The most significant changes include fixing the submodule filter logic, updating full-text search joins, and adding a summary of retests to the reports view.
* Corrected the submodule filter in `defect_controller.rb` to use `qa_module_id` instead of `submodule_id`, ensuring accurate filtering by submodule.
* Removed `submodule` from `.includes` and `.left_joins` in `defect_controller.rb`, streamlining queries and preventing unnecessary table joins. [[1]](diffhunk://#diff-dc7c49831e0ad3c9799f5217bbb1c0a4a030855fdaf4eaad445020b5d6b37d17L58-R58) [[2]](diffhunk://#diff-dc7c49831e0ad3c9799f5217bbb1c0a4a030855fdaf4eaad445020b5d6 …
=> Ball equation

.idea/copilot.data.migration.ask.xml, .idea/copilot.data.migration.ask2agent.xml, app/controllers/reports_controller.rb, app/views/reports/index.html.erb, config/environments/staging.rb, config/routes.rb, db/schema.rb
This pull request introduces several enhancements and structural changes, primarily focused on the reporting functionality and database schema updates. The most significant changes include the addition of CSV export for defect reports, updates to the reports controller and views, modifications to the database schema to support new Motor tables, and some environment and routing adjustments.
**Reporting Feature Enhancements**
* Added a new `export_csv` action to `ReportsController` for exporting filtered defect reports as CSV, including a helper method for CSV generation.
* Updated the reports index view (`index.html.erb`) to include a "Download CSV" button when a product is selected, allowing users to easily export defect data.
* Updated routes to support the new `export_csv` endpoint for …
=> Report fix deport fix

app/controllers/comments_controller.rb, app/controllers/defect_controller.rb, app/controllers/issues_controller.rb, app/controllers/tickets_controller.rb, app/models/ability.rb, app/views/comments/_comment.html.erb, app/views/issues/_message.html.erb, app/views/tickets/_action_dropdown.html.erb
This pull request removes the ability to delete tickets, issues, and comments from the application by disabling both the controller actions and the corresponding UI elements. The destroy actions for these resources have been commented out in their respective controllers, and all related delete buttons or links in the views have been commented out to prevent users from accessing the delete functionality.
**Removal of destroy functionality in controllers:**
* `app/controllers/tickets_controller.rb`, `app/controllers/issues_controller.rb`, `app/controllers/comments_controller.rb`: The `destroy` actions for tickets, issues, and comments have been commented out, effectively disabling the backend logic for deleting these resources. The corresponding `before_action` filters for destroy have also …
=> Add CSV export functionality for defect reports and update routes

app/javascript/controllers/ckeditor_init.js, app/views/defect/_content_defect.html.erb
CKeditor tables and list items. Handles issue #240
=> CKeditor tables and list items

app/javascript/controllers/defect_linking_controller.js, app/views/defect/new.html.erb
- Reload to update page after linking defects
- Onfocus drop down for Defcets asisgnee, projects and banking types
=> Dropdown onfocus

app/controllers/defect_controller.rb, app/views/defect/show.html.erb, app/views/profiles/profiles_show_user.html.erb
This pull request refactors several sections of the ticket and defect views to improve maintainability and consistency by replacing inline logic with partials and updating some UI elements. The main changes include extracting ticket priority, status, and progress bar rendering into dedicated partials, and updating headings and spacing in the defect summary and description.
**Refactoring for maintainability and consistency:**
* Replaced inline logic for rendering ticket priority with the `tickets/priority_severity` partial in `profiles_show_user.html.erb`.
* Replaced the detailed case statement for ticket statuses with the `tickets/ticket_status` partial in `profiles_show_user.html.erb`.
* Moved the progress bar rendering for ticket progress into the `tickets/progress_bar` partial in …
=> Tickets fix

app/controllers/defect_controller.rb, app/javascript/controllers/modal_controller.js, app/views/defect/_form_labels.html.erb, app/views/defect/edit.html.erb, app/views/defect/new.html.erb
1. Re order the defect new form according to the requested flow as per the provided document
2. SHow banking types and modules, sub modules for a project and not for all
3. Do not prefil the projects section only do that when a user selects something
4. Close the form when you click outside
=> Defectfixes

app/controllers/defect_controller.rb, app/views/defect/_top_bar_show.html.erb
=> Fix the validation error that is occurring in bug creation

app/controllers/banking_types_controller.rb
Fix error preventing the banking types from creating where there is no 'product_id' scope
=> Fix error preventing the banking types from creating where there is no 'product_id' scope

app/controllers/banking_types_controller.rb, app/controllers/defect_controller.rb, app/controllers/qa_modules_controller.rb, app/javascript/controllers/label_editor_controller.js, app/views/banking_types/_form.html.erb, app/views/defect/_labels.html.erb, app/views/qa_modules/_form.html.erb, app/views/qa_modules/index.html.erb
Fix defect issues noticed on create
=> Fixshow allqamodules bankingtypes oncreate

app/views/product/_product_index_topbar.html.erb
This pull request refactors the `product_index_topbar` partial to use utility-first CSS classes (likely from Tailwind CSS) instead of custom styles, improving maintainability and consistency with the rest of the codebase. The changes enhance the responsive layout, accessibility, and visual appearance of the filter bar and its controls, while removing the embedded `<style>` block.
**Styling and Layout Refactor:**
* Replaced custom CSS classes and the embedded `<style>` block with utility classes for colors, spacing, borders, and responsiveness throughout the filter bar and its controls. (`app/views/product/_product_index_topbar.html.erb`) [[1]](diffhunk://#diff-5912ddf5d8d6add4e7472564b6173709779007a87fc3fdb52782c5d32dcf1f6cL1-R37) …
=> Refactor product filter bar for improved layout

app/controllers/product_controller.rb, app/models/task.rb, app/views/tasks/_card.html.erb, app/views/tasks/_form.html.erb, app/views/tasks/edit.html.erb
This pull request enhances the handling and display of prerequisite tasks for product tasks, improves CSV export functionality, and adds clarity to task selection in forms. The main changes include updating the CSV export to include prerequisite and date fields, improving the display of prerequisite tasks in the UI, and making it easier to identify tasks in selection lists by showing their unique IDs.
**CSV Export Improvements**
* The `download_tasks_csv` method now exports additional fields: prerequisite task name, start date, and end date. The CSV filename also includes groupware names and uses a more readable date format.
**Task Selection and Display Enhancements**
* Added a new `name_with_unique_id` method to the `Task` model, allowing tasks to be displayed with both their unique ID …
=> Fixed product add all
