db/migrate/20250818119321_create_banking_types.rb

This pull request makes small improvements to the migration for the `banking_types` table. The changes ensure that the table and its index are only created if they do not already exist, which helps prevent migration errors during repeated runs.

Banking fix types

---

app/views/defect/_defect.html.erb
db/schema.rb

This pull request makes improvements to the defect summary display and updates the schema for defect records. The most important changes include increasing the visible length of defect summaries in the UI and making the `summary` field optional in the database.
**UI improvements:**
* Increased the width of the `Summary` column in the defect table by adding the `w-1/3` class to improve readability.
* Increased the truncation limit for defect summaries from 30 to 70 characters, allowing more of the summary to be visible in the UI.
**Database schema update:**
* Made the `summary` field optional (removed `null: false` constraint) in the `defects` table to allow defect records without a summary.

Make `summary` optional and adjust defect view for improved readability.

---

app/controllers/data_center_controller.rb
app/controllers/defect_controller.rb
app/views/data_center/user_report.html.erb
app/views/tickets/_ticket_user_initials.html.erb
app/views/tickets/_timeline.html.erb
app/views/tickets/_timeline_down.html.erb
app/views/tickets/show.html.erb

This pull request introduces improvements to ticket reporting and enhances the ticket timeline UI. The main changes include adding an average assignment-to-resolution time metric to the user report, updating the timeline display with user initials or profile pictures, and refactoring timeline rendering for better visual clarity.
**Reporting enhancements:**
* Added calculation of the average time from assignment to resolution for resolved tickets in the `user_report` controller action (`app/controllers/data_center_controller.rb`).
* Displayed the computed average assignment-to-resolution time in the user report table footer, including a human-readable format and ticket count (`app/views/data_center/user_report.html.erb`).
**Timeline UI improvements:**
* Created a new partial, …

Timeline fixed down

---

app/controllers/defect_controller.rb
app/controllers/defect_messages_controller.rb
app/controllers/home_controller.rb
app/controllers/tickets_controller.rb
app/views/defect/index.html.erb
app/views/home/index.html.erb
app/views/tickets/show_all_tickets_user_inactive.html.erb
config/routes.rb
db/schema.rb

This pull request introduces a new feature to display tickets created by inactive users, along with UI and controller updates to support this functionality. It also includes minor improvements to pagination and code consistency, as well as a schema change to allow nullable defect summaries.
**New Feature: Inactive User Tickets**
* Added `show_all_tickets_user_inactive` action to `TicketsController`, which lists tickets created by inactive users, supports searching, and paginates results.
* Created the corresponding view `tickets/show_all_tickets_user_inactive.html.erb` for displaying the tickets in a table with pagination controls.
* Updated routes to include the new endpoint for showing tickets by inactive users.
* Enhanced the home page UI to link to the new inactive tickets view if the …

This is the status defect fix

---

app/views/defect_messages/_defect_message.html.erb
app/views/defect_messages/_message.html.erb
app/views/defect_messages/_messages.html.erb
app/views/defect_messages/edit.html.erb

Defect messages currently use a rich text editor (Action Text), but users cannot attach files directly within the editor. We need to extend the functionality to allow users to attach files (images, videos, documents, etc.) inside the rich text editor, and display these attachments properly in the comments section.
This will enhance defect collaboration by letting users add screenshots, logs, and other files directly within the context of their message.
On edit of a defect message/ delete of a defect message, refresh the page to update the view of available defect messages.
This PR handles this issue #73

Support File Attachments in Defect Messages (Rich Text Editor)

---

app/controllers/defect_controller.rb
app/javascript/controllers/status_filter_controller.js
app/views/defect/_defect.html.erb
app/views/defect/_top_bar.html.erb

On the Defects Index page, we want to add a status filter dropdown that dynamically lists only the statuses currently present among the displayed defects. When a user selects a status, the page should filter and display only defects that match that status.
This will help users quickly narrow down defects without cluttering the filter with unused statuses.

Dynamic filter for defect index

---

app/controllers/defect_controller.rb
app/models/ability.rb

This pull request primarily expands and refines role-based permissions for the `hod` (Head of Department) and `project manager` roles in the `Ability` model, while also simplifying conditional logic in the `DefectController`. The changes improve maintainability and clarity, and ensure that users with specific roles have the correct access to features.
**Role-based permissions updates:**
* Expanded permissions for the `hod` role to include managing `Project`, `Product`, `Board`, `Task`, `Team`, and generating reports, while restricting certain actions like deleting products and managing admin users.
* Refined permissions for the `project manager` role, removing access to tickets created by inactive users and clarifying ticket-related actions.
**Codebase simplification:**
* Streamlined …

Permission fixed fix

---

app/views/defect/_defect_order_status.html.erb
db/schema.rb

This pull request introduces a couple of targeted improvements to the defect order status view and updates the database schema. The most notable change is making the product and client name clickable, linking to the product's detail page, which enhances navigation for users. Additionally, the `summary` field in the defects table is now nullable, allowing for more flexibility in defect records.
**User interface enhancement:**
* Made the product and client name in the defect order status table a clickable link to the product detail page, improving navigation and user experience (`app/views/defect/_defect_order_status.html.erb`).
**Database schema update:**
* Changed the `summary` column in the `defects` table to allow null values, increasing flexibility for defect entries (`db/schema.rb`).

Ability change to ensure users are able to get the details

---

app/views/defect/edit.html.erb
app/views/defect/new.html.erb

This pull request updates the modal dialogs for creating and editing defects to improve their layout and responsiveness. The most important changes involve adjusting the width and height of the modal containers to better fit the viewport.
**UI/UX Improvements:**
* In `app/views/defect/edit.html.erb`, the modal width is now set to `w-[90%]` instead of `w-full max-w-4xl`, allowing the edit defect modal to use 90% of the viewport width for a more consistent and responsive appearance.
* In `app/views/defect/new.html.erb`, the modal dimensions are changed to `w-[90%] h-[90%]`, making the new defect modal occupy 90% of both the width and height of the viewport, which enhances usability on various screen sizes.

Form size screen

---

app/controllers/qa_modules_controller.rb
app/models/project.rb
app/models/qa_module.rb
app/views/banking_types/new.html.erb
app/views/qa_modules/_form.html.erb
app/views/qa_modules/new.html.erb
db/migrate/20250829115235_add_product_to_qa_modules.rb
db/schema.rb

This pull request introduces support for associating each QA module with a product, improving data relationships and enabling more contextual selection and filtering in the UI. The changes include backend model updates, controller logic enhancements, database migrations, and user interface improvements to ensure QA modules are linked to products and that users can select the relevant product when creating or editing a QA module.
**Backend and Database Changes**
* Added a `belongs_to :product` association to the `QaModule` model, and updated the `Project` model to reference associated QA modules. [[1]](diffhunk://#diff-b4c02c091e28bf6350d362d39a9b668caae4ecdec1260ff573b4dd91954cd36aR2) [[2]](diffhunk://#diff-611e7045e8b0212d101cd856c335296959519af63b80129f51c246a7bbfe7b91R24)
* Added a …

Product module connection

---

app/controllers/defect_controller.rb
app/javascript/controllers/project_modules_controller.js
app/models/defect.rb
app/views/defect/_form.html.erb
app/views/defect/edit.html.erb
config/routes.rb
db/schema.rb

When creating a new Defect, the user should first select a Project. Once a project is chosen, only the QA Modules that belong to that project should be available in the dropdown. This ensures that defects are always tied to the correct module within the chosen project.
Currently, all QA Modules are listed, which is confusing and error-prone. By scoping modules to the selected project, we improve data integrity and user experience.

Filter QA Modules by Selected Project When Creating a Defect

---

app/views/defect/_defect_show_modal.html.erb

Since the defect labels were removed from the defect table, I now get them from the labels table instead

Defect Quick View labels error fix

---

app/views/defect/new.html.erb

This pull request updates the modal close button in the `app/views/defect/new.html.erb` file for the "New Defect" page. Instead of using a link to navigate away, it now uses a button that calls `history.back()` to close the modal, improving the user experience by returning users to their previous state.
User interface improvements:
* Replaced the `link_to` close button with a styled `<button>` that uses `history.back()` for navigation, providing a more intuitive modal closing behavior.

Replace close link with a button to improve modal navigation

---

app/controllers/defect_controller.rb
app/views/tasks/_card.html.erb

This pull request makes a minor update to the logic for displaying the task ID in the task card partial. The change ensures that the presence check is performed on the `task` object rather than specifically on its `unique_task_id` attribute.
* Updated the conditional in `app/views/tasks/_card.html.erb` to check if `task` is present before displaying `unique_task_id`, improving robustness in cases where the task object may be nil.

Add task name display to task details view

---

app/controllers/defect_controller.rb
app/controllers/tasks_controller.rb
app/mailers/user_mailer.rb
app/views/tasks/_content_for_task.erb
app/views/user_mailer/edit_defect_email.html.erb
app/views/user_mailer/new_defect_email.html.erb

This pull request adds automated email notifications for defect creation and updates, improves task management by supporting descriptions, and enhances the user interface to display task descriptions. The most significant changes are grouped below:
**Defect Notification Emails:**
* Added `new_defect_email` and `edit_defect_email` methods to `UserMailer` to send emails to both the defect creator and assigned users when a defect is created or edited.
* Updated `defect_controller.rb` to trigger these emails after creating or updating a defect. [[1]](diffhunk://#diff-dc7c49831e0ad3c9799f5217bbb1c0a4a030855fdaf4eaad445020b5d6b37d17R252-R254) [[2]](diffhunk://#diff-dc7c49831e0ad3c9799f5217bbb1c0a4a030855fdaf4eaad445020b5d6b37d17R348-R349)
* Created new email templates …

Defect new email

---

app/mailers/user_mailer.rb
config/environments/staging.rb

This pull request updates the default sender email address in the `UserMailer` to use a different address for the staging environment. This helps ensure that emails sent from staging are easily distinguishable from those sent from production.
Email configuration update:
* Changed the default `from` address in `user_mailer.rb` to use `taskbridgestaging@craftsilicon.com` in staging and `cspm@craftsilicon.com` in production and other environments.

Email staging

---

app/models/project.rb
app/views/project/_project_table.html.erb
app/views/project/show.html.erb
db/schema.rb

This works on this issue #261 
Users can now see the average rating for a service desk when they go to the service desk show page.

Aggregate client rating for service desk

---

app/javascript/controllers/defect_linking_controller.js

When linking a defect, show a green success message.

show success when linking a defect making it dependant on the other one

---

.idea/copilotDiffState.xml
app/controllers/defect_controller.rb
app/views/defect/_top_bar_show.html.erb
app/views/defect/index_show.html.erb

This pull request enhances the defect CSV download feature by adding support for multiple new filters and improving the user interface for downloading filtered defect data. The main focus is on making the CSV export more flexible and aligned with the available filtering options in the UI.
**Enhancements to CSV Download Functionality:**
* Added support for filtering defects by assignee, search query (client or groupware), banking type, date range, status (multi-select), priority, module, submodule, and labels (multi-select) in the `defects_download` action. The CSV can now be generated based on these filters.
* Improved the ordering of defects in the CSV export, allowing sorting by `created_at` in ascending or descending order based on user input.
**User Interface Updates:**
* Updated the …

Add CSV download functionality for defects

---

app/controllers/tickets_controller.rb
app/mailers/user_mailer.rb
app/views/user_mailer/status_update_email.html.erb

This pull request updates the ticket status notification system to improve how status update emails are sent and displayed. The changes ensure that relevant users are notified appropriately and that email content is accurate.
**Email notification logic:**
* Updated `add_status` in `tickets_controller.rb` to send status update emails to ticket users for most status changes, and to all project users when a ticket is reopened.
**Email delivery and content:**
* Modified `status_update_email` in `user_mailer.rb` to include the ticket's user as a BCC recipient, ensuring they receive status updates even if not the direct recipient.
* Fixed the service desk name in the email template to reference the ticket's project title for accuracy.

Tickets send to all

---

app/controllers/defect_controller.rb
app/views/banking_types/index.html.erb
app/views/defect/new.html.erb

Filter to show the defects of a client and the product_id only
Ensure that the banking type does not break when you do not have any banking types
Disable the projects dropdown to prevent a user from selecting another project accidentally as everything else is preloaded for the user

Defects indexshow filterproperly

---

app/views/project/_assign_people.html.erb
app/views/project/manage_users.html.erb

This pull request updates the user assignment interface in the project views to clarify the distinction between "Clients" and "Craft Silicon Staff" and improves the header for managing users. The main changes involve swapping the order and labeling of user groups in the assignment partial, as well as a minor header text update.
**User assignment interface improvements:**
* Swapped the display order of user groups in `app/views/project/_assign_people.html.erb`, now showing "Clients" first and "Craft Silicon Staff" second. The corresponding variables were updated to match the labels, ensuring that `@non_craft_silicon_users` are shown under "Clients" and `@craft_silicon_users` under "Craft Silicon Staff". [[1]](diffhunk://#diff-c46895eed9b550a7d39e4a66d8fdb76e5ea361dff06ef3a43e6619f7e8eb8148L …

Support desk user management realign

---

app/views/project/show.html.erb

This pull request updates the project overview UI to display the total number of open tickets instead of the SLA on target response. The label, icon, value, and filter link have all been changed to reflect this new focus.
UI changes to ticket statistics:
* Changed the label from "SLA on Target Response" to "All Open Tickets" in `app/views/project/show.html.erb`.
* Updated the icon SVG to better represent open tickets rather than SLA.
* Replaced the displayed value from `@sla_on_target` to `@total_tickets_open`.
* Modified the filter link to use `filter: 'Open'` instead of `filter: 'sla'`.

Update SLA section to display total open tickets instead
